spring.application.name=JWT_security

spring.datasource.url=jdbc:mysql://localhost:3306/spring_security_jwt?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=pass@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT config
jwt.secret=2f94a8d2baee6c43b8f72d9b147e8aa1d5c3f98bf6ab447c9ed228fa5dbf67c1

jwt.expiration-ms=900000

#
#server.port=8080


