spring.application.name=oAuth
spring.security.oauth2.client.registration.google.client-id=83655730844-2ijlkvrf330ckcorr7df9o08cek4eorg.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile